Qa krishan
gem-divyamadan/hris-ui-automation pull request #2
Opened 2023-04-26 13:14 UTC by gem-krishanpandey

@gem-rishabhrastogi please review the code.

2023-05-02 08:46 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/hris/commonUtils/HrisUtils.java
>              GemTestReporter.addTestStep("Check visibility of Login Button", "Login button is not present", STATUS.FAIL, takeSnapShot());
Not a good idea to throw an exception inside the catch block.

2023-05-02 08:47 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/hris/commonUtils/HrisUtils.java
>                      System.out.println("Please enter a valid Input");
Please refrain from using S.O.P statements. If you want some message to be printed out to user, it must be added as a step in your report.

2023-05-02 08:49 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/hris/commonUtils/HrisUtils.java
>      public void login() {
Not a good idea to create two functions with similar meanings (login() and signIn())

2023-05-02 08:51 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/hris/commonUtils/HrisUtils.java
>          try {
In readProperties() - The properties file path should not be hard-coded here.

2023-05-02 08:53 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/hris/commonUtils/TrainingUtils.java
> +            }
Add the else case to cover the scenario when field is somehow not present on screen.

2023-05-02 08:55 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/hris/locators/LoginLocators.java
> +    public static By image = By.xpath("//img[@class='img-pos']");
Assign meaningful names to variables

2023-05-02 08:56 UTC, gem-rishabhrastogi requested changes
Added some suggestions. Please work on those.

2023-05-10 12:55 UTC, gem-rishabhrastogi approved these changes
Good to go.

2023-05-22 12:02 UTC, gem-krishanpandey commented
Hi @gem-rishabhrastogi kindly review the code.

2023-05-24 12:41 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/hris/stepDefinition/Training.java
>      public void userSelectsTheirExperience() {
Take experience as an argument from the feature file

2023-05-24 12:45 UTC, gem-rishabhrastogi requested changes
Added a couple of suggestions. Please work on those.

2023-05-25 09:58 UTC, gem-rishabhrastogi approved these changes
Good to go.

2023-05-26 05:44 UTC, merged